/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.agendapoo.view;

import classes.Contatos;
import classes.Pessoa;
import classes.PessoaFisica;
import classes.PessoaJuridica;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author guilhermecarvalho
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdFisica = new javax.swing.JRadioButton();
        rdJuridica = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agenda");

        buttonGroup1.add(rdFisica);
        rdFisica.setText("Física");
        rdFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFisicaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdJuridica);
        rdJuridica.setText("Jurídica");

        txtNome.setText("Nome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtCpf.setText("CPF / CNPJ");

        txtEmail.setText("E-mail");

        txtContato.setText("Contato");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jList1ComponentRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Contatos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdFisica)
                                .addGap(18, 18, 18)
                                .addComponent(rdJuridica))
                            .addComponent(btCadastrar)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNome)
                    .addComponent(txtCpf)
                    .addComponent(txtEmail)
                    .addComponent(txtContato))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(448, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(405, 405, 405))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdFisica)
                    .addComponent(rdJuridica))
                .addGap(18, 18, 18)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void rdFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFisicaActionPerformed

    public boolean cadValidate () {
        boolean validate = true;
        if (!rdFisica.isSelected() && !rdJuridica.isSelected()) {
            validate = false;
            JOptionPane.showMessageDialog(null, "É necessário selecionar um tipo de pessoa!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
        if (txtNome.getText() == null && txtNome.getText().trim().isEmpty()) {
            validate = false;
            JOptionPane.showMessageDialog(null, "É necessário digitar um nome!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
        if (txtCpf.getText() == null && txtCpf.getText().trim().isEmpty()) {
            validate = false;
            JOptionPane.showMessageDialog(null, "É necessário digitar um Cpf!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
        if (txtEmail.getText() == null && txtEmail.getText().trim().isEmpty()) {
            validate = false;
            JOptionPane.showMessageDialog(null, "É necessário digitar um email!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
        if (txtContato.getText() == null && txtContato.getText().trim().isEmpty()) {
            validate = false;
            JOptionPane.showMessageDialog(null, "É necessário digitar um telefone!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
        
        return validate;
    }
    
    
    DefaultListModel grid = new DefaultListModel();
        
    private void fillGrid(Pessoa pessoa) {
        jList1.setModel(grid);
        grid.addElement(pessoa instanceof PessoaFisica ? ((PessoaFisica)pessoa).toString() : ((PessoaJuridica)pessoa).toString());
    }
    
    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        if (cadValidate()) {
            Contatos contatos = new Contatos();
            Pessoa pessoa;
            if(rdFisica.isSelected()) {
                PessoaFisica pf = new PessoaFisica();
                pf.setCpf(txtCpf.getText());
                pf.setNome(txtNome.getText());
                pf.setEmail(txtEmail.getText());
                pf.setTelefone(txtContato.getText());
                pessoa = (PessoaFisica) pf;
            } else {
                PessoaJuridica pj = new PessoaJuridica();
                pj.setCnpj(txtCpf.getText());
                pj.setNome(txtNome.getText());
                pj.setEmail(txtEmail.getText());
                pj.setTelefone(txtContato.getText());
                pessoa = (PessoaJuridica) pj;
            }
            contatos.addPessoas(pessoa);
            fillGrid(pessoa);
            JOptionPane.showMessageDialog(null, "Cadastro concluído!", "Aviso!", JOptionPane.WARNING_MESSAGE); 
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível efetuar o cadastro!", "Alerta!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void jList1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jList1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdFisica;
    private javax.swing.JRadioButton rdJuridica;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
